version: "3"

services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /food_professor/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/food_professor
      - gem_data:/usr/local/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - db
      - chrome

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444

  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      # node_modulesを入れるvolume
      - node-volume:/usr/src/food_professor/react-app/node_modules
    command: sh -c "cd react-app && yarn start"
    ports:
      - "8000:3000"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASS}
      MYSQL_ROOT_PASSWORD: ${MYSQLROOTPASS}
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  # databaseのデータ保存用
  db-data:
  # gemの永続化用
  gem_data:
  # node_modulesをホストのvolumeに
  node-volume:
